<?php

namespace StoresSuite\Wix\Services;

use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Redirect;
use StoresSuite\Wix\Models\WixSite;
use Illuminate\Http\RedirectResponse;
use StoresSuite\Wix\Models\WixAccessToken;

class WixAppService
{
    /**
     * Redirect to app's dashboard
     *
     * @param WixSite $wixSite
     * @return RedirectResponse
     */
    public function redirectToDashboard(WixSite $wixSite)
    {
        $appId = Config::get('wix.app_id');
        $appDashboardUrl = 'https://manage.wix.com/dashboard/' . $wixSite->_id . '/app/' . $appId;
        return Redirect::to($appDashboardUrl);
    }

    /**
     * Redirect to installation page
     *
     * @param string $token - Token provided by Wix when user tries to install app.
     * @param string|null $state - State is generated by our app and supplied to Wix.
     * @return RedirectResponse
     */
    public function redirectToInstallationPage(string $token, string $state = null)
    {
        $appId = Config::get('wix.app_id');
        $redirectUrl = Config::get('wix.redirect_url');
        $installationUrl = Config::get('wix.installation_url') . '?appId=' . $appId . '&redirectUrl=' . $redirectUrl;

        if ($token) {
            $installationUrl .= '&token=' . $token;
        }

        if ($state) {
            $installationUrl .= '&state=' . $state;
        }

        return Redirect::to($installationUrl);
    }

    /**
     * Close window - Wix requires us to close installation window by redirecting user to 'close window' URL
     * after installation. Wix will automatically redirect users to app's dashboard after that.
     *
     * @param WixAccessToken $wixAccessToken
     * @return RedirectResponse
     */
    public function closeWindow(WixAccessToken $wixAccessToken)
    {
        $closeWindowUrl = 'https://www.wix.com/installer/close-window?access_token=' . $wixAccessToken->token();
        return Redirect::to($closeWindowUrl);
    }
}
